# -*- coding: utf-8 -*-
"""Currency Counter1

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1irTzKnN8QqbWpwBi62kQJRFE_zmElXpy
"""

LITERS_PER_GALLON = 3.78541
GALLONS_PER_LITER = 0.264172
CAD_TO_USD = 0.76
USD_TO_CAD = 1.31



def unit_converter(units, total_cost,from_currency,to_currency):
  Answer = 0
  #cost_per_unit = total_cost/units
  if (from_currency == "$" and to_currency == "C$"):
    Answer = (total_cost/units)*(GALLONS_PER_LITER*USD_TO_CAD)
  elif (from_currency == "C$" and to_currency == "$"):
    Answer = (total_cost/units)*(LITERS_PER_GALLON*CAD_TO_USD)
  elif (from_currency == "$" and to_currency == "$"):
    Answer = (total_cost/units)
  elif (from_currency == "C$" and to_currency == "C$"):
    Answer = (total_cost/units)
  
  return Answer


  
CAD_per_liter  = unit_converter(16, 45.0, '$', 'C$')
print(CAD_per_liter)

USD_per_gallon = unit_converter(61, 124.00, 'C$', '$')
print(USD_per_gallon)

USD_per_gallon = unit_converter(16, 45.0, '$', '$')
print(USD_per_gallon)

USD_per_gallon = unit_converter(16, 124.00, 'C$', 'C$')
print(USD_per_gallon)

print("$", unit_converter(61, 124.00, 'C$', '$'), "per gallon")
print(unit_converter(16, 45.0, '$', 'C$'))